### ISSUE TITLE
Missing types in npm package ?

### ISSUE THREAD

**Issue by muka** [punkpeye/fastmcp#2]
hi, I tried to follow the setup instructions in a TS project
After installing `npm install -s fastmcp` I get 

`Cannot find module 'fastmcp' or its corresponding type declarations.`

![image](https://github.com/user-attachments/assets/2418c216-399e-4bed-9608-9f390ace9b19)

**Comment by punkpeye** [comment]
Fixed in https://github.com/punkpeye/fastmcp/commit/721f328ab402fecbeb1838a99b9aa36d1bb1ea07. Thank you for reporting
